# 1. THE JEDI TRICK (Same as before)
LIBGCC_PATH := $(shell $(CC) -mcpu=cortex-a8 -mfloat-abi=hard -mfpu=neon -print-libgcc-file-name)

# 2. Toolchain Override
CC = $(CROSS_COMPILE)gcc
AS = $(CROSS_COMPILE)as
LD = $(CROSS_COMPILE)ld
OBJCOPY = $(CROSS_COMPILE)objcopy

MKIMAGE = /home/shangavelan/BSP_builds/BBB/revc-yocto-og/build/tmp/work/beaglebone-poky-linux-gnueabi/u-boot-bb.org/2025.10+git/build/tools/mkimage

# --- Include Directories ---
# Adding more folders is easy: INCLUDES = -Iinclude -Idrivers/include
INCLUDES = -Iinclude -Iarch

# --- Strict Bare-Metal Flags ---
# Added -MD to generate dependency files (.d)
CFLAGS = -mcpu=cortex-a8 -marm -mfpu=neon -mfloat-abi=hard \
         -ffreestanding -nostdlib -O2 $(INCLUDES) -MD
ASFLAGS = -mcpu=cortex-a8 -mfpu=neon
LDFLAGS = -T memmap.ld

# --- Auto-Discovery ---
#C_SRCS = $(wildcard *.c) $(wildcard drivers/*.c) $(wildcard libs/*.c) $(wildcard drivers/nonstart/*.c) $(wildcard libs/*/*.c) $(wildcard application/*.c)

C_SRCS = main.c \
         application/mmcsd_app.c \
         libs/mmcsd/mmc_library.c

# Main Drivers
C_SRCS += drivers/mmcsd.c \
		  #drivers/gpio.c

# Non-Starterware Low-Level Drivers
C_SRCS += drivers/nonstart/clock_module.c \
          drivers/nonstart/control_module.c \
          drivers/nonstart/pad.c \
          drivers/nonstart/UART.c \
		  drivers/nonstart/GPIO.c \
		  #drivers/nonstart/LED.o \
          #drivers/nonstart/wdt_control.c
C_OBJS = $(C_SRCS:.c=.o)
ASM_OBJS = arch/start.o

# Grab all the .d files generated by -MD
DEPS = $(C_OBJS:.o=.d)

OBJS = $(ASM_OBJS) $(C_OBJS)

all: MLO

# Include the dependency rules if they exist
-include $(DEPS)

# Pattern rule for C files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Explicit rule for assembly
arch/start.o: arch/start.s
	$(AS) $(ASFLAGS) $< -o $@

# 3. Link explicitly
main.elf: $(OBJS) memmap.ld
	$(LD) $(LDFLAGS) arch/start.o $(filter-out arch/start.o, $(OBJS)) $(LIBGCC_PATH) -o $@

main.bin: main.elf
	$(OBJCOPY) -O binary $< $@

MLO: main.bin
	$(MKIMAGE) -T omapimage -a 0x402F0400 -d $< $@

clean:
	rm -f $(OBJS) $(DEPS) main.elf main.bin MLO